---

# sources:
# - https://docs.gitea.com/installation/install-with-docker-rootless

version: '2'

services:
  server:
    image: gitea/gitea:1.22.2-rootless
    restart: unless-stopped
    volumes:
      - data:/var/lib/gitea
      - config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 2222:2222

volumes:
  config:
  data:
