Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/focal64"
    config.vm.provider "virtualbox" do |virtualbox|
        virtualbox.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
        virtualbox.memory = 1024
        virtualbox.cpus = 1
    end
    config.vm.provision "shell", inline: <<-SHELL
        apt update
        apt -y install parallel
    SHELL

    (1..3).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.hostname = "node-#{i}"
        end
    end

    config.vm.define "special_node", primary: true do |special_node|
        special_node.vm.network "private_network", ip: "192.168.56.101", name: "VirtualBox Host-Only Ethernet Adapter"
        special_node.vm.hostname = "special_node"
        special_node.vm.provider "virtualbox" do |virtualbox|
            virtualbox.memory = 2048
            virtualbox.cpus = 2
        end
        special_node.vm.provision "shell", inline: <<-SHELL
            apt -y install tmux
        SHELL
    end
