---
# See https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml for more information.

default: true

MD013:  # line-length
  line_length: 120
  tables: false
  code_blocks: false
MD033:  # no-inline-html
  allowed_elements:
    - br
    - code
    - details
    - summary
    - sup
