---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages:
          - commit-msg
        additional_dependencies:
          - '@commitlint/config-conventional'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-xml
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md   # ignore markdown's line break
      - id: end-of-file-fixer
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        args:
          - -r "~MD013"   # ignore line-length rule
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint
  # - repo: https://github.com/ansible-community/ansible-lint
  #   # FIXME: need to figure this out, too many stupid issues.
  #   # Using `ansible-lint -v ansible` for the time being.
  #   rev: v6.19.0
  #   hooks:
  #     - id: ansible-lint
  #       exclude: .*
  #       files: ansible/
