---
# See https://yamllint.readthedocs.io/en/stable/configuration.html for
# more information.

extends: default

rules:
  comments:
    ignore:
      - 'cloud-init/*'
      - 'examples/cloud-init/*'
      - 'examples/terraform/multi-part cloud-init/*'
  document-start:
    ignore:
      - 'cloud-init/*'
      - 'examples/cloud-init/*'
      - 'examples/terraform/multi-part cloud-init/*'
  line-length:
    level: warning
    max: 120
    allow-non-breakable-inline-mappings: true
