---
version: 3

includes:
  python: taskfiles/python.yml

tasks:

  dev-tools:bootstrap:
    cmds:
      - task: python:create-venv
      - npm install

  dev-tools:update:
    cmds:
      - task: python:update-venv
      - npm update --save

  show-platform:
    silent: true
    cmds:
      - 'echo "OS: {{OS}}"'
      - 'echo "ARCH: {{ARCH}}"'
