---
version: '3'

includes:
  python: taskfiles/python.yml

vars:
  REQUIREMENTS_FILE: '{{ .ROOT_DIR }}/requirements.txt'
  VENV_DIR: '{{ .ROOT_DIR }}/.venv'

tasks:

  dev-tools:bootstrap:
    cmds:
      - task: python:create-venv
      - npm install

  dev-tools:update:
    cmds:
      - task: python:update-venv
      - npm update --save
