#cloud-config

##
# Tested on:
# - RHEL 8.6
##

write_files:
  - path: /etc/cron.daily/security-updates
    permissions: '0755'
    content: |
      #!/bin/bash
      dnf -y upgrade --security --nobest
    defer: true
