---
# See https://github.com/syncthing/syncthing/blob/main/README-Docker.md
version: "3"
services:
  syncthing:
    image: syncthing/syncthing:1.27.7
    container_name: syncthing
    hostname: ${HOSTNAME}
    environment:
      - PUID=1000
      - PGID=100
    volumes:
      - config:/var/syncthing/config
      - ${PWD}/data:/var/syncthing/data
    network_mode: host
    restart: unless-stopped

volumes:
  config:
