"""
Scheduled Resource Controller

On-demand Lambda for starting and stopping non-production AWS resources (EC2, RDS, ECS, ASG).
See README.md for the full specification.

Routes:
- POST /slack/start, /slack/stop for Slack slash commands (HMAC-verified, channel-allowlisted)
- POST /api/iam/start, /api/iam/stop for IAM-authenticated HTTP (SigV4 at API Gateway)
- EventBridge Scheduler direct invoke {action, source: 'scheduler'}

Implementation notes
--------------------
Every request expands to *units* (one alias = one unit; all inline scheduler specs = one unit; one Slack/IAM body = one
unit). Units run in parallel. Within a unit, `dependsOn` references create topological levels processed sequentially.

`RESOURCE_REGISTRY` maps token-grammar keys to specs with optional `dependsOn`.
Aliases and scheduler targets list leaf resources. Dependencies are auto-included from the registry. Inline/alias specs
win on deduplication, with the registry merging its `dependsOn` onto existing specs.

Check readiness using boto3 waiters where AWS provides them (`db_instance_available`, `services_stable`,
`instance_running`, `instance_stopped`), fallback to bounded polling where it does not (autoscaling has no waiters;
RDS has no `stopped` waiter).

Slack's synchronous handler verifies the signature and returns a 200 within 3s, then self-invokes asynchronously
(InvocationType='Event') for the actual work. The async continuation posts results to Slack via `response_url`.

One paginated `describe_alarms` call per invocation builds a dimension-value-to-alarm-names map. Client-side filtering
is required (DescribeAlarms has no server-side dimension filter).
Alarm-level exclusion tags are fetched via `resourcegroupstaggingapi.get_resources` at index build time.
"""

import hashlib
import hmac
import json
import logging
import os
import time
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from typing import Any, Callable

import boto3
from botocore.exceptions import WaiterError

logger = logging.getLogger()
logger.setLevel(logging.INFO)

EXCLUDE_TAG_KEY = 'ops:excludeFromScheduledStop'

# -----------------------------------------------------------------------------
# Configuration.
# Read once at cold start.
# -----------------------------------------------------------------------------

REGION = os.environ.get('AWS_REGION', 'eu-west-1')

# Configuration is bundled as `config.json` in the Lambda package (generated by IaC at deploy time) to stay under the
# 4KB Lambda environment-variable limit. Environment variables override values in `config.json` when set.
_CONFIG_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'config.json')
if os.path.exists(_CONFIG_PATH):
    with open(_CONFIG_PATH) as _f:
        _config = json.load(_f)
else:
    _config = {}

SLACK_SIGNING_SECRET_ID: str = os.environ.get('SLACK_SIGNING_SECRET_ID') or _config.get('slackSigningSecretId', '')
ALLOWED_CHANNEL_IDS: set[str] = set(
    json.loads(os.environ['ALLOWED_SLACK_CHANNEL_IDS']) if 'ALLOWED_SLACK_CHANNEL_IDS' in os.environ
    else _config.get('allowedSlackChannelIds', [])
)

# Named aliases: maps "staging.core" -> [{"type": "asg", "name": "..."}, ...]
RESOURCE_ALIASES: dict[str, list[dict[str, Any]]] = (
    json.loads(os.environ['RESOURCE_ALIASES']) if 'RESOURCE_ALIASES' in os.environ
    else _config.get('aliases', {})
)

# Per-resource default counts for restoring ECS/ASG on start (any invocation path).
# Keys: "asg:<asg-name>" or "ecs:<cluster>:<service>". Missing key -> 1.
DEFAULT_COUNTS: dict[str, int] = (
    json.loads(os.environ['DEFAULT_COUNTS']) if 'DEFAULT_COUNTS' in os.environ
    else _config.get('defaultCounts', {})
)

# Opt-in scheduler target lists. Each item is a string (alias name or registry key) or an inline spec dict.
NIGHTLY_STOP_TARGETS: list = (
    json.loads(os.environ['NIGHTLY_STOP_TARGETS']) if 'NIGHTLY_STOP_TARGETS' in os.environ
    else _config.get('nightlyStopTargets', [])
)
MORNING_START_TARGETS: list = (
    json.loads(os.environ['MORNING_START_TARGETS']) if 'MORNING_START_TARGETS' in os.environ
    else _config.get('morningStartTargets', [])
)

# Resource registry: maps token-grammar keys to specs with optional dependsOn for auto-expansion.
RESOURCE_REGISTRY: dict[str, dict[str, Any]] = (
    json.loads(os.environ['RESOURCE_REGISTRY']) if 'RESOURCE_REGISTRY' in os.environ
    else _config.get('resourceRegistry', {})
)

# Slack docs: reject events older than 5 minutes to prevent replay attacks.
SLACK_REQUEST_MAX_AGE_SECONDS = 300

# Dependency-set wait budgets.
# Waits happen only *between* dependency levels inside one unit; final levels never wait. Budgets must keep the worst
# sequential chain inside the Lambda timeout (900s) with headroom for the API calls themselves and the Slack callback.
WAITER_DELAY_SECONDS = 15
POLL_INTERVAL_SECONDS = 10
STOP_WAIT_MAX_SECONDS = 300   # ECS drain / ASG terminate typically completes within 1-3 minutes
START_WAIT_MAX_SECONDS = 720  # RDS start typically takes 5-12 minutes

# boto3 clients
# Defined at module-level for warm-invocation reuse
_ec2 = boto3.client('ec2', region_name=REGION)
_ecs = boto3.client('ecs', region_name=REGION)
_rds = boto3.client('rds', region_name=REGION)
_secrets = boto3.client('secretsmanager', region_name=REGION)
_lambda = boto3.client('lambda', region_name=REGION)
_asg = boto3.client('autoscaling', region_name=REGION)
_cw = boto3.client('cloudwatch', region_name=REGION)
_tagging = boto3.client('resourcegroupstaggingapi', region_name=REGION)

_slack_signing_secret_cache: str | None = None

# Alarm index: dimension value -> list of alarm names.
# Built lazily on first use per invocation, reset at handler() entry to prevent stale warm-container state.
_alarm_cache: dict[str, list[str]] | None = None


def _slack_signing_secret() -> str:
    global _slack_signing_secret_cache
    if _slack_signing_secret_cache is None:
        resp = _secrets.get_secret_value(SecretId=SLACK_SIGNING_SECRET_ID)
        _slack_signing_secret_cache = resp['SecretString']
    return _slack_signing_secret_cache


# -----------------------------------------------------------------------------
# Entry point
# -----------------------------------------------------------------------------

def handler(event: dict[str, Any], context: Any) -> dict[str, Any]:
    global _alarm_cache
    _alarm_cache = None
    if event.get('source') == 'scheduler':
        return _handle_scheduler(event)
    if event.get('isAsync'):
        return _handle_slack_async(event)

    path = event.get('resource') or event.get('path', '')
    if path == '/slack/start':
        return _handle_slack(event, context, 'start')
    if path == '/slack/stop':
        return _handle_slack(event, context, 'stop')
    if path == '/api/iam/start':
        return _handle_iam(event, 'start')
    if path == '/api/iam/stop':
        return _handle_iam(event, 'stop')
    return _api_response(404, {'error': f'unknown route: {path}'})


# -----------------------------------------------------------------------------
# Slack routes (synchronous: verify, ack, async self-invoke)
# -----------------------------------------------------------------------------

def _handle_slack(event: dict[str, Any], context: Any, action: str) -> dict[str, Any]:
    headers = {k.lower(): v for k, v in (event.get('headers') or {}).items()}
    body = event.get('body') or ''
    if not _verify_slack_signature(headers, body):
        return _api_response(403, {'error': 'invalid Slack signature'})

    parsed = urllib.parse.parse_qs(body)
    channel_id = parsed.get('channel_id', [''])[0]
    if channel_id not in ALLOWED_CHANNEL_IDS:
        return _slack_text(f'channel `{channel_id}` is not in the allowlist')

    text = parsed.get('text', [''])[0].strip()
    response_url = parsed.get('response_url', [''])[0]
    if not response_url.startswith('https://hooks.slack.com/'):
        return _slack_text('unexpected response_url; cannot proceed')

    command = f'/{action}-aws-resource'
    try:
        units = _parse_slack_units(text, action)
    except ValueError as e:
        counts = '[:count]' if action == 'start' else ''
        return _slack_text(
            f'parse error: {e}\n'
            f'usage: `{command} <alias>` or `{command} ec2:i-abc rds:my-db ecs:cluster:service{counts} asg:my-asg{counts}`'
        )

    # Async self-invoke: Slack expects a 200 within 3 seconds.
    caller = f"{parsed.get('user_name', [''])[0]} ({parsed.get('user_id', [''])[0]})"
    try:
        _lambda.invoke(
            FunctionName=context.function_name,
            InvocationType='Event',
            Payload=json.dumps({
                'isAsync': True,
                'action': action,
                'units': units,
                'response_url': response_url,
                'caller': caller,
            }).encode(),
        )
    except Exception:
        return _slack_text('failed to queue work; try again in a moment')
    verb = 'starting' if action == 'start' else 'stopping'
    total = sum(len(unit['resources']) for unit in units)
    return _slack_text(f'{verb} {total} resource(s)...')


def _handle_slack_async(event: dict[str, Any]) -> dict[str, Any]:
    units = event.get('units')
    if units is None:
        units = [{'name': None, 'resources': event.get('resources', [])}]
    results = _process_units(units)
    _post_to_slack(event['response_url'], _format_for_slack(results))
    action = event.get('action', 'start')
    _log_run(action, 'slack', event.get('caller', 'unknown'), results)
    return {'isAsync': True, 'results': results}


# -----------------------------------------------------------------------------
# IAM-auth routes (synchronous: SigV4 already verified by API Gateway)
# -----------------------------------------------------------------------------

def _handle_iam(event: dict[str, Any], action: str) -> dict[str, Any]:
    """
    One request = one dependency set. Specs may declare `dependsOn` (token-grammar keys) for ordering.

    Requests whose graph triggers between-level waits can exceed API Gateway's 29s integration timeout;
    the caller then receives a 504 while the Lambda completes the work. Callers needing synchronous results
    should split independent resources into separate requests.
    """
    try:
        body = json.loads(event.get('body') or '{}')
        resources = body['resources']
    except (json.JSONDecodeError, KeyError, TypeError) as e:
        return _api_response(400, {'error': f'malformed body: {e}'})
    if not isinstance(resources, list):
        return _api_response(400, {'error': '`resources` must be a list'})
    results = _process_units([_make_unit([dict(r) for r in resources], action)])
    caller = ((event.get('requestContext') or {}).get('identity') or {}).get('userArn', 'unknown')
    _log_run(action, 'iam_http', caller, results)
    return _api_response(_status_for(results), {'results': results})


def _status_for(results: list[dict[str, Any]]) -> int:
    """
    HTTP status for a synchronous batch response.

    200: every resource succeeded (acted, or already in the requested state).
    207 Multi-Status: mixed outcomes; per-resource detail in the body.
    403: every resource was refused by the safety rails.
    500: every resource failed.
    """
    errors = [r for r in results if r.get('status') != 'ok']
    if not errors:
        return 200
    if len(errors) < len(results):
        return 207
    if all(r.get('message', '').startswith('refused') for r in errors):
        return 403
    return 500


# -----------------------------------------------------------------------------
# Scheduler route (EventBridge Scheduler)
# -----------------------------------------------------------------------------

def _log_run(
    action: str,
    source: str,
    caller: str,
    results: list[dict[str, Any]],
) -> None:
    ok      = [r for r in results if r.get('status') == 'ok']
    acted   = [r for r in ok      if not r.get('message', '').startswith('already')]
    skipped = [r for r in ok      if r.get('message', '').startswith('already')]
    errors  = [r for r in results if r.get('status') != 'ok']
    logger.info(json.dumps({
        'action':  action,
        'source':  source,
        'caller':  caller,
        'total':   len(results),
        'acted':   len(acted),
        'skipped': len(skipped),
        'errors':  len(errors),
        'results': results,
    }))


def _handle_scheduler(event: dict[str, Any]) -> dict[str, Any]:
    action = event.get('action')
    if action not in ('stop', 'start'):
        return {'error': f'unknown scheduler action: {action}'}

    targets = NIGHTLY_STOP_TARGETS if action == 'stop' else MORNING_START_TARGETS
    units = _expand_units(targets, action)
    for unit in units:
        for resource in unit['resources']:
            resource['source'] = 'scheduler'
    results = _process_units(units)
    _log_run(action, 'scheduler', 'scheduler', results)

    errors = [r for r in results if r.get('status') != 'ok']
    if errors:
        # Fail loud so Lambda error alarms fire. Idempotent verbs make async-invoke retries safe.
        raise RuntimeError(f'scheduler {action}: {len(errors)} of {len(results)} resource(s) failed; see structured log entry')
    return {'action': action, 'count': len(results), 'results': results}


# -----------------------------------------------------------------------------
# Units
# -----------------------------------------------------------------------------

def _make_unit(
    resources: list[dict[str, Any]], action: str, name: str | None = None, *, merge_registry: bool = True,
) -> dict[str, Any]:
    resources = _resolve_registry_deps(resources, merge=merge_registry)
    stamped = []
    for spec in resources:
        spec = {**spec, 'action': action}
        if action == 'start':
            spec = _apply_start_counts(spec)
        stamped.append(spec)
    return {'name': name, 'resources': stamped}


def _alias_unit(alias: str, action: str) -> dict[str, Any]:
    specs = RESOURCE_ALIASES.get(alias)
    if specs is None:
        raise ValueError(f'unknown alias `{alias}`; available: {list(RESOURCE_ALIASES.keys())}')
    return _make_unit([dict(spec) for spec in specs], action, name=alias)


def _apply_start_counts(spec: dict[str, Any]) -> dict[str, Any]:
    if spec.get('type') == 'ecs' and 'desiredCount' not in spec:
        return {**spec, 'desiredCount': DEFAULT_COUNTS.get(_resource_key(spec), 1)}
    if spec.get('type') == 'asg' and 'desiredCapacity' not in spec:
        return {**spec, 'desiredCapacity': DEFAULT_COUNTS.get(_resource_key(spec), 1)}
    return spec


def _expand_units(items: list, action: str) -> list[dict[str, Any]]:
    units: list[dict[str, Any]] = []
    inline_specs: list[dict[str, Any]] = []
    for item in items:
        if isinstance(item, str):
            if ':' in item:
                spec = RESOURCE_REGISTRY.get(item)
                if spec is None:
                    raise ValueError(f'registry key `{item}` not found in RESOURCE_REGISTRY')
                inline_specs.append(dict(spec))
            else:
                units.append(_alias_unit(item, action))
        else:
            inline_specs.append(dict(item))
    if inline_specs:
        units.append(_make_unit(inline_specs, action, merge_registry=False))
    return units


# -----------------------------------------------------------------------------
# Slack helpers
# -----------------------------------------------------------------------------

def _verify_slack_signature(headers: dict[str, str], body: str) -> bool:
    timestamp = headers.get('x-slack-request-timestamp', '')
    signature = headers.get('x-slack-signature', '')
    if not timestamp or not signature:
        return False
    try:
        if abs(time.time() - int(timestamp)) > SLACK_REQUEST_MAX_AGE_SECONDS:
            return False
    except ValueError:
        return False
    base = f'v0:{timestamp}:{body}'.encode()
    expected = 'v0=' + hmac.new(_slack_signing_secret().encode(), base, hashlib.sha256).hexdigest()
    return hmac.compare_digest(expected, signature)


def _parse_slack_units(text: str, action: str) -> list[dict[str, Any]]:
    """
    Parse a slash-command text into units.

    - If any token contains ':', all tokens are resource specs forming one anonymous unit.
    - Otherwise, tokens joined with '.' name an alias (e.g. 'staging core' -> 'staging.core').
    """
    if not text:
        raise ValueError('empty command; pass an alias or at least one resource spec')
    tokens = text.split()
    if any(':' in token for token in tokens):
        return [_make_unit(_parse_slack_text(text), action)]
    return [_alias_unit('.'.join(tokens), action)]


def _parse_slack_text(text: str) -> list[dict[str, Any]]:
    """
    Parse `<type>:<id>[:<extra>]` whitespace-separated tokens into resource specs.

    - `ec2:<instance-id>`
    - `rds:<db-instance-identifier>`
    - `ecs:<cluster>:<service>[:<desiredCount>]`
    - `asg:<asg-name>[:<desiredCapacity>]`
    """
    if not text:
        raise ValueError('empty command; pass at least one resource')

    resources: list[dict[str, Any]] = []
    for token in text.split():
        parts = token.split(':')
        rtype = parts[0].lower()
        if rtype in ('ec2', 'rds') and len(parts) == 2:
            resources.append({'type': rtype, 'id': parts[1]})
        elif rtype == 'ecs' and len(parts) in (3, 4):
            spec: dict[str, Any] = {'type': 'ecs', 'cluster': parts[1], 'service': parts[2]}
            if len(parts) == 4:
                spec['desiredCount'] = int(parts[3])
            resources.append(spec)
        elif rtype == 'asg' and len(parts) in (2, 3):
            spec = {'type': 'asg', 'name': parts[1]}
            if len(parts) == 3:
                spec['desiredCapacity'] = int(parts[2])
            resources.append(spec)
        else:
            raise ValueError(f'malformed token `{token}`')
    return resources


def _format_for_slack(results: list[dict[str, Any]]) -> str:
    errors = [r for r in results if r.get('status') != 'ok']
    lines = []
    if errors:
        lines.append(f'[!] {len(errors)} of {len(results)} resource(s) failed')
    for r in results:
        tag = '[ok]' if r.get('status') == 'ok' else '[err]'
        ident = r.get('id') or r.get('name') or f"{r.get('cluster', '?')}/{r.get('service', '?')}"
        lines.append(f"{tag} *{r.get('type')}* `{ident}`: {r.get('message', '')}")
    return '\n'.join(lines)


def _post_to_slack(url: str, text: str) -> None:
    payload = json.dumps({'text': text, 'response_type': 'in_channel'}).encode()
    req = urllib.request.Request(url, data=payload, headers={'Content-Type': 'application/json'})
    try:
        with urllib.request.urlopen(req, timeout=5) as resp:
            resp.read()
    except Exception:
        pass


def _slack_text(text: str) -> dict[str, Any]:
    return {
        'statusCode': 200,
        'headers': {'Content-Type': 'application/json'},
        'body': json.dumps({'response_type': 'ephemeral', 'text': text}),
    }


def _api_response(status: int, body: dict[str, Any]) -> dict[str, Any]:
    return {
        'statusCode': status,
        'headers': {'Content-Type': 'application/json'},
        'body': json.dumps(body),
    }


# -----------------------------------------------------------------------------
# Dependency graph
# -----------------------------------------------------------------------------

def _resource_key(spec: dict[str, Any]) -> str:
    rtype = spec.get('type')
    if rtype == 'ecs':
        return f"ecs:{spec.get('cluster')}:{spec.get('service')}"
    if rtype == 'asg':
        return f"asg:{spec.get('name')}"
    return f"{rtype}:{spec.get('id')}"


def _topo_levels(resources: list[dict[str, Any]]) -> list[list[dict[str, Any]]]:
    """
    Group a unit's resources into dependency levels

    Uses Kahn's algorithm.
    Returns levels in *start* order: dependencies first. Stop processing reverses the list.
    """
    by_key: dict[str, dict[str, Any]] = {}
    for resource in resources:
        key = _resource_key(resource)
        if key in by_key:
            raise ValueError(f'duplicate resource `{key}` in set')
        by_key[key] = resource

    pending: dict[str, set[str]] = {}
    for key, resource in by_key.items():
        deps = set(resource.get('dependsOn', []))
        unknown = deps - by_key.keys()
        if unknown:
            raise ValueError(f'`{key}` depends on unknown resource(s): {sorted(unknown)}')
        pending[key] = deps

    levels: list[list[dict[str, Any]]] = []
    while pending:
        ready = sorted(key for key, deps in pending.items() if not deps)
        if not ready:
            raise ValueError(f'dependency cycle among: {sorted(pending)}')
        levels.append([by_key[key] for key in ready])
        for key in ready:
            del pending[key]
        for deps in pending.values():
            deps.difference_update(ready)
    return levels


def _resolve_registry_deps(resources: list[dict[str, Any]], *, merge: bool = True) -> list[dict[str, Any]]:
    by_key: dict[str, dict[str, Any]] = {}
    for r in resources:
        by_key[_resource_key(r)] = r

    if merge:
        for key in list(by_key):
            reg = RESOURCE_REGISTRY.get(key)
            if reg and 'dependsOn' in reg:
                spec = by_key[key]
                merged = sorted(set(spec.get('dependsOn', [])) | set(reg['dependsOn']))
                by_key[key] = {**spec, 'dependsOn': merged}

    visited = set(by_key)
    queue: list[str] = []
    for spec in by_key.values():
        for dep in spec.get('dependsOn', []):
            if dep not in visited:
                queue.append(dep)
                visited.add(dep)

    while queue:
        key = queue.pop(0)
        reg = RESOURCE_REGISTRY.get(key)
        if reg is None:
            continue
        spec = dict(reg)
        by_key[key] = spec
        for dep in spec.get('dependsOn', []):
            if dep not in visited:
                queue.append(dep)
                visited.add(dep)

    return list(by_key.values())


# -----------------------------------------------------------------------------
# Readiness / drain checks
# -----------------------------------------------------------------------------

def _poll_until(check: Callable[[], bool], timeout_seconds: int) -> bool:
    deadline = time.monotonic() + timeout_seconds
    while time.monotonic() < deadline:
        if check():
            return True
        time.sleep(POLL_INTERVAL_SECONDS)
    return False


def _run_waiter(client: Any, waiter_name: str, waiter_kwargs: dict[str, Any], timeout_seconds: int) -> bool:
    attempts = max(1, timeout_seconds // WAITER_DELAY_SECONDS)
    try:
        client.get_waiter(waiter_name).wait(
            **waiter_kwargs,
            WaiterConfig={'Delay': WAITER_DELAY_SECONDS, 'MaxAttempts': attempts},
        )
        return True
    except WaiterError:
        return False


def _wait_stopped(resource: dict[str, Any]) -> bool:
    rtype = resource.get('type')
    try:
        if rtype == 'ec2':
            return _run_waiter(_ec2, 'instance_stopped', {'InstanceIds': [resource['id']]}, STOP_WAIT_MAX_SECONDS)
        if rtype == 'ecs':
            return _run_waiter(
                _ecs, 'services_stable',
                {'cluster': resource['cluster'], 'services': [resource['service']]},
                STOP_WAIT_MAX_SECONDS,
            )
        if rtype == 'rds':
            return _poll_until(
                lambda: _rds.describe_db_instances(DBInstanceIdentifier=resource['id'])
                        ['DBInstances'][0]['DBInstanceStatus'] == 'stopped',
                STOP_WAIT_MAX_SECONDS,
            )
        if rtype == 'asg':
            return _poll_until(
                lambda: not _asg.describe_auto_scaling_groups(AutoScalingGroupNames=[resource['name']])
                        ['AutoScalingGroups'][0].get('Instances'),
                STOP_WAIT_MAX_SECONDS,
            )
    except Exception:
        return False
    return False


def _wait_ready(resource: dict[str, Any]) -> bool:
    rtype = resource.get('type')
    try:
        if rtype == 'ec2':
            return _run_waiter(_ec2, 'instance_running', {'InstanceIds': [resource['id']]}, START_WAIT_MAX_SECONDS)
        if rtype == 'ecs':
            return _run_waiter(
                _ecs, 'services_stable',
                {'cluster': resource['cluster'], 'services': [resource['service']]},
                START_WAIT_MAX_SECONDS,
            )
        if rtype == 'rds':
            return _run_waiter(
                _rds, 'db_instance_available', {'DBInstanceIdentifier': resource['id']}, START_WAIT_MAX_SECONDS,
            )
        if rtype == 'asg':
            def _at_capacity() -> bool:
                group = _asg.describe_auto_scaling_groups(AutoScalingGroupNames=[resource['name']])['AutoScalingGroups'][0]
                in_service = [i for i in group.get('Instances', []) if i.get('LifecycleState') == 'InService']
                return group.get('DesiredCapacity', 0) > 0 and len(in_service) >= group['DesiredCapacity']
            return _poll_until(_at_capacity, START_WAIT_MAX_SECONDS)
    except Exception:
        return False
    return False


# -----------------------------------------------------------------------------
# Alarm suppression
# -----------------------------------------------------------------------------

def _alarm_index() -> dict[str, list[str]]:
    global _alarm_cache
    if _alarm_cache is not None:
        return _alarm_cache

    excluded_names: set[str] = set()
    try:
        paginator = _tagging.get_paginator('get_resources')
        for page in paginator.paginate(
            ResourceTypeFilters=['cloudwatch:alarm'],
            TagFilters=[{'Key': EXCLUDE_TAG_KEY, 'Values': ['true']}],
        ):
            for resource in page.get('ResourceTagMappingList', []):
                arn = resource.get('ResourceARN', '')
                parts = arn.split(':alarm:', 1)
                if len(parts) == 2:
                    excluded_names.add(parts[1])
    except Exception:
        logger.warning('failed to fetch excluded alarm tags; proceeding without alarm-level exclusion')

    index: dict[str, list[str]] = {}
    paginator = _cw.get_paginator('describe_alarms')
    for page in paginator.paginate(AlarmTypes=['MetricAlarm']):
        for alarm in page.get('MetricAlarms', []):
            name = alarm['AlarmName']
            if name in excluded_names:
                continue
            if not alarm.get('AlarmActions') and not alarm.get('OKActions') and not alarm.get('InsufficientDataActions'):
                continue
            for dim in alarm.get('Dimensions', []):
                index.setdefault(dim['Value'], []).append(name)

    _alarm_cache = index
    return index


def _alarms_for_resource(resource: dict[str, Any]) -> list[str]:
    index = _alarm_index()
    rtype = resource.get('type')
    if rtype in ('ec2', 'rds'):
        return index.get(resource.get('id', ''), [])
    if rtype == 'ecs':
        service_alarms = set(index.get(resource.get('service', ''), []))
        cluster_alarms = set(index.get(resource.get('cluster', ''), []))
        return sorted(service_alarms & cluster_alarms)
    if rtype == 'asg':
        return index.get(resource.get('name', ''), [])
    return []


def _set_alarm_actions(resource: dict[str, Any], result: dict[str, Any], *, enabled: bool) -> None:
    if result.get('alarmExcluded'):
        return
    msg = result.get('message', '')
    if msg.startswith('excluded:'):
        return

    alarms = _alarms_for_resource(resource)
    if not alarms:
        return

    action_word = 'enable' if enabled else 'disable'
    try:
        if enabled:
            _cw.enable_alarm_actions(AlarmNames=alarms)
        else:
            _cw.disable_alarm_actions(AlarmNames=alarms)
        logger.info(json.dumps({
            'alarmAction': action_word,
            'resource': _resource_key(resource),
            'alarms': alarms,
        }))
        result_key = 'alarmsEnabled' if enabled else 'alarmsDisabled'
        result[result_key] = len(alarms)
    except Exception as e:
        if enabled:
            # Fail loud: a running resource with muted alarms is the incident this exists to prevent.
            result['status'] = 'error'
            result['message'] = f"{msg}; alarm re-enable failed: {e}"
        else:
            # Best-effort: the resource stop is the goal; alarm noise is secondary.
            logger.warning('alarm disable failed for %s: %s', _resource_key(resource), e)


# -----------------------------------------------------------------------------
# Resource processing
# -----------------------------------------------------------------------------

def _process_units(units: list[dict[str, Any]]) -> list[dict[str, Any]]:
    if not units:
        return []
    with ThreadPoolExecutor(max_workers=10) as pool:
        per_unit = list(pool.map(_process_unit, units))
    return [result for unit_results in per_unit for result in unit_results]


def _process_unit(unit: dict[str, Any]) -> list[dict[str, Any]]:
    resources = unit.get('resources', [])
    if not resources:
        return []
    try:
        levels = _topo_levels(resources)
    except ValueError as e:
        return [{**r, 'status': 'error', 'message': f'invalid dependency set: {e}'} for r in resources]

    action = resources[0].get('action', 'start')
    if action == 'stop':
        levels.reverse()

    results: list[dict[str, Any]] = []
    upstream_not_stopped = False
    for index, level in enumerate(levels):
        if upstream_not_stopped:
            results.extend(
                {**r, 'status': 'error', 'message': 'skipped: upstream resources not confirmed stopped'}
                for r in level
            )
            continue

        level_results = [_process_one(r) for r in level]
        results.extend(level_results)

        if action == 'stop':
            for resource, result in zip(level, level_results):
                if result.get('status') == 'ok':
                    _set_alarm_actions(resource, result, enabled=False)

        is_final = index == len(levels) - 1

        if is_final:
            if action == 'start':
                for resource, result in zip(level, level_results):
                    if result.get('status') == 'ok':
                        _set_alarm_actions(resource, result, enabled=True)
            continue

        for resource, result in zip(level, level_results):
            failed_call = result.get('status') != 'ok'
            excluded = result.get('message', '').startswith('excluded:')
            if action == 'stop':
                if failed_call or excluded:
                    upstream_not_stopped = True
                elif not _wait_stopped(resource):
                    result['status'] = 'error'
                    result['message'] = f"{result.get('message', '')}; not confirmed stopped within {STOP_WAIT_MAX_SECONDS}s"
                    upstream_not_stopped = True
            else:
                if not failed_call and not _wait_ready(resource):
                    result['status'] = 'error'
                    result['message'] = f"{result.get('message', '')}; not ready within {START_WAIT_MAX_SECONDS}s (dependents started anyway)"
                if not failed_call:
                    _set_alarm_actions(resource, result, enabled=True)
    return results


def _process_one(resource: dict[str, Any]) -> dict[str, Any]:
    rtype = resource.get('type')
    action = resource.get('action', 'start')
    source = resource.get('source')
    try:
        if rtype == 'ec2':
            return _stop_ec2(resource['id'], source=source) if action == 'stop' else _start_ec2(resource['id'], source=source)
        if rtype == 'rds':
            return _stop_rds(resource['id'], source=source) if action == 'stop' else _start_rds(resource['id'], source=source)
        if rtype == 'ecs':
            if action == 'stop':
                return _stop_ecs(resource['cluster'], resource['service'], source=source)
            return _start_ecs(resource['cluster'], resource['service'], resource.get('desiredCount', 1), source=source)
        if rtype == 'asg':
            if action == 'stop':
                return _stop_asg(resource['name'], source=source)
            return _start_asg(resource['name'], resource.get('desiredCapacity', 1), source=source)
        return {**resource, 'status': 'error', 'message': f'unknown type `{rtype}`'}
    except Exception as e:
        return {**resource, 'status': 'error', 'message': str(e)}


def _check_environment(tags: list[dict[str, str]]) -> str | None:
    env = next((t['Value'] for t in tags if t.get('Key') == 'Environment'), None)
    if env is None:
        return 'refused: no Environment tag'
    if env == 'Production':
        return 'refused: production'
    return None


def _check_exclude(tags: list[dict[str, str]], source: str | None) -> str | None:
    if source != 'scheduler':
        return None
    value = next((t['Value'] for t in tags if t.get('Key') == EXCLUDE_TAG_KEY), None)
    if value == 'true':
        return f'excluded: {EXCLUDE_TAG_KEY}'
    return None


# -----------------------------------------------------------------------------
# Start verbs
# -----------------------------------------------------------------------------

def _start_ec2(instance_id: str, *, source: str | None = None) -> dict[str, Any]:
    desc = _ec2.describe_instances(InstanceIds=[instance_id])
    reservations = desc.get('Reservations', [])
    if not reservations or not reservations[0].get('Instances'):
        return {'type': 'ec2', 'id': instance_id, 'status': 'error', 'message': 'not found'}
    inst = reservations[0]['Instances'][0]
    arn = f"arn:aws:ec2:{REGION}:{reservations[0]['OwnerId']}:instance/{instance_id}"
    tags = inst.get('Tags', [])
    rejection = _check_environment(tags)
    if rejection:
        return {'type': 'ec2', 'id': instance_id, 'arn': arn, 'status': 'error', 'message': rejection}
    state = inst.get('State', {}).get('Name')
    if state in ('running', 'pending'):
        result = {'type': 'ec2', 'id': instance_id, 'arn': arn, 'status': 'ok', 'message': f'already {state}'}
    else:
        _ec2.start_instances(InstanceIds=[instance_id])
        result = {'type': 'ec2', 'id': instance_id, 'arn': arn, 'status': 'ok', 'message': 'started'}
    if _check_exclude(tags, source):
        result['alarmExcluded'] = True
    return result


def _start_rds(db_id: str, *, source: str | None = None) -> dict[str, Any]:
    desc = _rds.describe_db_instances(DBInstanceIdentifier=db_id)
    instances = desc.get('DBInstances', [])
    if not instances:
        return {'type': 'rds', 'id': db_id, 'status': 'error', 'message': 'not found'}
    inst = instances[0]
    arn = inst['DBInstanceArn']
    tags = _rds.list_tags_for_resource(ResourceName=arn).get('TagList', [])
    rejection = _check_environment(tags)
    if rejection:
        return {'type': 'rds', 'id': db_id, 'arn': arn, 'status': 'error', 'message': rejection}
    state = inst.get('DBInstanceStatus')
    if state in ('available', 'starting', 'configuring-enhanced-monitoring'):
        result = {'type': 'rds', 'id': db_id, 'arn': arn, 'status': 'ok', 'message': f'already {state}'}
    else:
        _rds.start_db_instance(DBInstanceIdentifier=db_id)
        result = {'type': 'rds', 'id': db_id, 'arn': arn, 'status': 'ok', 'message': 'started'}
    if _check_exclude(tags, source):
        result['alarmExcluded'] = True
    return result


def _start_ecs(cluster: str, service: str, desired_count: int, *, source: str | None = None) -> dict[str, Any]:
    desc = _ecs.describe_services(cluster=cluster, services=[service], include=['TAGS'])
    services = desc.get('services', [])
    if not services:
        return {'type': 'ecs', 'cluster': cluster, 'service': service, 'status': 'error', 'message': 'not found'}
    svc = services[0]
    arn = svc['serviceArn']
    # ECS tags use lowercase key/value; normalize for _check_environment.
    normalized_tags = [{'Key': t['key'], 'Value': t['value']} for t in svc.get('tags', [])]
    rejection = _check_environment(normalized_tags)
    if rejection:
        return {'type': 'ecs', 'cluster': cluster, 'service': service, 'arn': arn, 'status': 'error', 'message': rejection}
    current = svc.get('desiredCount', 0)
    if current >= desired_count:
        result = {'type': 'ecs', 'cluster': cluster, 'service': service, 'arn': arn, 'status': 'ok', 'message': f'already at desiredCount={current}'}
    else:
        _ecs.update_service(cluster=cluster, service=service, desiredCount=desired_count)
        result = {'type': 'ecs', 'cluster': cluster, 'service': service, 'arn': arn, 'status': 'ok', 'message': f'desiredCount {current} -> {desired_count}'}
    if _check_exclude(normalized_tags, source):
        result['alarmExcluded'] = True
    return result


def _start_asg(asg_name: str, desired_capacity: int, *, source: str | None = None) -> dict[str, Any]:
    desc = _asg.describe_auto_scaling_groups(AutoScalingGroupNames=[asg_name])
    groups = desc.get('AutoScalingGroups', [])
    if not groups:
        return {'type': 'asg', 'name': asg_name, 'status': 'error', 'message': 'not found'}
    group = groups[0]
    arn = group['AutoScalingGroupARN']
    tags = group.get('Tags', [])
    rejection = _check_environment(tags)
    if rejection:
        return {'type': 'asg', 'name': asg_name, 'arn': arn, 'status': 'error', 'message': rejection}
    current = group.get('DesiredCapacity', 0)
    current_min = group.get('MinSize', 0)
    needs_min_restore = current_min == 0
    if current >= desired_capacity and not needs_min_restore:
        result = {'type': 'asg', 'name': asg_name, 'arn': arn, 'status': 'ok', 'message': f'already at desiredCapacity={current}'}
    else:
        kwargs: dict = {'DesiredCapacity': desired_capacity}
        if needs_min_restore:
            kwargs['MinSize'] = 1
        _asg.update_auto_scaling_group(AutoScalingGroupName=asg_name, **kwargs)
        msg = f'desiredCapacity {current} -> {desired_capacity}'
        if needs_min_restore:
            msg += ', MinSize 0 -> 1'
        result = {'type': 'asg', 'name': asg_name, 'arn': arn, 'status': 'ok', 'message': msg}
    if _check_exclude(tags, source):
        result['alarmExcluded'] = True
    return result


# -----------------------------------------------------------------------------
# Stop verbs
# -----------------------------------------------------------------------------

def _stop_ec2(instance_id: str, *, source: str | None = None) -> dict[str, Any]:
    desc = _ec2.describe_instances(InstanceIds=[instance_id])
    reservations = desc.get('Reservations', [])
    if not reservations or not reservations[0].get('Instances'):
        return {'type': 'ec2', 'id': instance_id, 'status': 'error', 'message': 'not found'}
    inst = reservations[0]['Instances'][0]
    arn = f"arn:aws:ec2:{REGION}:{reservations[0]['OwnerId']}:instance/{instance_id}"
    tags = inst.get('Tags', [])
    rejection = _check_environment(tags)
    if rejection:
        return {'type': 'ec2', 'id': instance_id, 'arn': arn, 'status': 'error', 'message': rejection}
    exclusion = _check_exclude(tags, source)
    if exclusion:
        return {'type': 'ec2', 'id': instance_id, 'arn': arn, 'status': 'ok', 'message': exclusion}
    state = inst.get('State', {}).get('Name')
    if state in ('stopped', 'stopping'):
        return {'type': 'ec2', 'id': instance_id, 'arn': arn, 'status': 'ok', 'message': f'already {state}'}
    _ec2.stop_instances(InstanceIds=[instance_id])
    return {'type': 'ec2', 'id': instance_id, 'arn': arn, 'status': 'ok', 'message': 'stopped'}


def _stop_rds(db_id: str, *, source: str | None = None) -> dict[str, Any]:
    desc = _rds.describe_db_instances(DBInstanceIdentifier=db_id)
    instances = desc.get('DBInstances', [])
    if not instances:
        return {'type': 'rds', 'id': db_id, 'status': 'error', 'message': 'not found'}
    inst = instances[0]
    arn = inst['DBInstanceArn']
    tags = _rds.list_tags_for_resource(ResourceName=arn).get('TagList', [])
    rejection = _check_environment(tags)
    if rejection:
        return {'type': 'rds', 'id': db_id, 'arn': arn, 'status': 'error', 'message': rejection}
    exclusion = _check_exclude(tags, source)
    if exclusion:
        return {'type': 'rds', 'id': db_id, 'arn': arn, 'status': 'ok', 'message': exclusion}
    state = inst.get('DBInstanceStatus')
    if state in ('stopped', 'stopping'):
        return {'type': 'rds', 'id': db_id, 'arn': arn, 'status': 'ok', 'message': f'already {state}'}
    _rds.stop_db_instance(DBInstanceIdentifier=db_id)
    return {'type': 'rds', 'id': db_id, 'arn': arn, 'status': 'ok', 'message': 'stopped'}


def _stop_ecs(cluster: str, service: str, *, source: str | None = None) -> dict[str, Any]:
    desc = _ecs.describe_services(cluster=cluster, services=[service], include=['TAGS'])
    services = desc.get('services', [])
    if not services:
        return {'type': 'ecs', 'cluster': cluster, 'service': service, 'status': 'error', 'message': 'not found'}
    svc = services[0]
    arn = svc['serviceArn']
    normalized_tags = [{'Key': t['key'], 'Value': t['value']} for t in svc.get('tags', [])]
    rejection = _check_environment(normalized_tags)
    if rejection:
        return {'type': 'ecs', 'cluster': cluster, 'service': service, 'arn': arn, 'status': 'error', 'message': rejection}
    exclusion = _check_exclude(normalized_tags, source)
    if exclusion:
        return {'type': 'ecs', 'cluster': cluster, 'service': service, 'arn': arn, 'status': 'ok', 'message': exclusion}
    current = svc.get('desiredCount', 0)
    if current == 0:
        return {'type': 'ecs', 'cluster': cluster, 'service': service, 'arn': arn, 'status': 'ok', 'message': 'already at desiredCount=0'}
    _ecs.update_service(cluster=cluster, service=service, desiredCount=0)
    return {'type': 'ecs', 'cluster': cluster, 'service': service, 'arn': arn, 'status': 'ok', 'message': f'desiredCount {current} -> 0'}


def _stop_asg(asg_name: str, *, source: str | None = None) -> dict[str, Any]:
    desc = _asg.describe_auto_scaling_groups(AutoScalingGroupNames=[asg_name])
    groups = desc.get('AutoScalingGroups', [])
    if not groups:
        return {'type': 'asg', 'name': asg_name, 'status': 'error', 'message': 'not found'}
    group = groups[0]
    arn = group['AutoScalingGroupARN']
    tags = group.get('Tags', [])
    rejection = _check_environment(tags)
    if rejection:
        return {'type': 'asg', 'name': asg_name, 'arn': arn, 'status': 'error', 'message': rejection}
    exclusion = _check_exclude(tags, source)
    if exclusion:
        return {'type': 'asg', 'name': asg_name, 'arn': arn, 'status': 'ok', 'message': exclusion}
    current_desired = group.get('DesiredCapacity', 0)
    current_min = group.get('MinSize', 0)
    if current_desired == 0 and current_min == 0:
        return {'type': 'asg', 'name': asg_name, 'arn': arn, 'status': 'ok', 'message': 'already at DesiredCapacity=0'}
    _asg.update_auto_scaling_group(AutoScalingGroupName=asg_name, DesiredCapacity=0, MinSize=0)
    return {
        'type': 'asg', 'name': asg_name, 'arn': arn, 'status': 'ok',
        'message': f'DesiredCapacity {current_desired} -> 0, MinSize {current_min} -> 0',
    }
