---

# https://nginxproxymanager.com/setup/
# https://nginxproxymanager.com/advanced-config/

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    environment:
      PUID: 1000
      PGID: 1000
    restart: unless-stopped
    ports:
      - '17080:80'
      - '17081:81'
      - '17443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
