---
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '17080:80'
      - '17081:81'
      - '17443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
