version: "3.2"
secrets:
  webpassword:
    file: ./webpassword
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2023.01.10
    environment:
      FTLCONF_LOCAL_IPV4: 127.0.0.1
      REV_SERVER_CIDR: 192.168.1.0/24
      REV_SERVER_DOMAIN: localdomain
      REV_SERVER_TARGET: 192.168.1.1
      REV_SERVER: "true"
      SKIPGRAVITYONBOOT: 1
      TZ: Europe/Amsterdam
      WEBPASSWORD_FILE: /run/secrets/webpassword
    volumes:
      - ./etc/pihole:/etc/pihole
      - ./etc/dnsmasq.d:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
    secrets:
      - webpassword
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
