Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"   # bleeding edge

  config.vm.provider "virtualbox" do |vb|
    vb.name = "xfce4 latest"
    vb.cpus = 1
    vb.memory = "2048"
    vb.gui = true
    vb.customize ["modifyvm", :id, "--vram", "64"]
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
  end

  config.vm.provision "shell", path: "../../scripts/arch linux/virtualbox-guest-utils.nox-to-x.sh"
  config.vm.provision "shell", path: "../../scripts/arch linux/xfce4.install.sh"
  config.vm.provision "shell", reboot: true
end
