---
# See https://hadolint.github.io/hadolint/ for more information

override:
  style:
    - DL3006  # always tag the version of an image explicitly
    - DL3008  # pin versions in apt get install
    - DL3013  # pin versions in pip
    - DL3015  # avoid additional packages by specifying `--no-install-recommends`
    - DL3018  # pin versions in apk add
