---
version: '3'
services:
  radar:
    container_name: radar
    image: nginxinc/nginx-unprivileged:1.25.5-bookworm-perl
    volumes:
      - ${PWD}/build:/usr/share/nginx/html/techradar:ro
    ports:
      - 8080:8080
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: '8080'
