---
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - 106  # 'render', but this group does not exist in the container
      - video
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - config:/config
      - target: /cache
        type: tmpfs
        tmpfs:
          mode: 0o01777
      - source: /tank/media
        target: /media
        type: bind
        read_only: true
    restart: unless-stopped
volumes:
  config:
