---

- name: Create the configuration file
  become: true
  ansible.builtin.template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: u=rw,g=,o=
    backup: true
  register: config_file
  notify:
    - "Validate Gitlab's configuration file"
    - Reconfigure Gitlab
