# gotchas:
# - 'pid: host' allows boinc to determine nonboinc processes for cpu percentages
#   and exclusive applications
#
# sources:
# - https://hub.docker.com/r/boinc/client
# - https://docs.docker.com/compose/compose-file/compose-file-v2/

version: '2'
services:
  client:
    image: boinc/client:arm32v7
    container_name: boinc-client
    restart: always
    network_mode: host
    pid: host
    volumes:
      - ${PWD}/data:/var/lib/boinc
    environment:
      - BOINC_CMD_LINE_OPTIONS=--allow_remote_gui_rpc
      - BOINC_GUI_RPC_PASSWORD=123
      - TZ=Europe/Dublin
