---

##
# Source:
# `helm template --namespace 'gitlab' --values "values.gitlab-runner.yaml" --set global.hosts.hostSuffix='test' \
#   'gitlab-runner' 'gitlab/gitlab-runner'`
##

useTini: false

image:
  registry: registry.gitlab.com
  image: gitlab-org/gitlab-runner
imagePullPolicy: IfNotPresent

gitlabUrl: https://gitlab.company.com/

unregisterRunners: true

terminationGracePeriodSeconds: 3600

concurrent: 10
shutdown_timeout: 0
checkInterval: 30

sessionServer:
  enabled: false

rbac:
  create: true
  generatedServiceAccountName: ""
  rules: []
  clusterWideAccess: false
  podSecurityPolicy:
    enabled: false
    resourceNames:
      - gitlab-runner

metrics:
  enabled: false
  portName: metrics
  port: 9252
  serviceMonitor:
    enabled: false

service:
  enabled: false
  type: ClusterIP

runners:
  config: |
    [[runners]]

      [runners.cache]
        Type = "s3"
        Path = "runner/"
        Shared = true
        MaxUploadedArchiveSize = 0

        [runners.cache.s3]
          ServerAddress = "s3.amazonaws.com"
          BucketName = "company-ci"
          BucketLocation = "eu-west-1"

      [runners.kubernetes]
        namespace = "{{.Release.Namespace}}"
        image = "alpine"
        pull_policy = [
          "if-not-present",
          "always"
        ]
        allowed_pull_policies = [
          "if-not-present",
          "always",
          "never"
        ]

  configPath: ""
  name: "test-runner-on-k8s"
  secret: gitlab-runner-token
  cache: {}

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  privileged: false
  capabilities:
    drop: ["ALL"]

strategy: {}

podSecurityContext:
  runAsUser: 100
  fsGroup: 65533

resources: {}

affinity: {}
topologySpreadConstraints: {}
nodeSelector: {}
tolerations: []

extraEnv: {}
extraEnvFrom: {}

hostAliases: []

deploymentAnnotations: {}
deploymentLabels:
  team: infra

podAnnotations: {}
podLabels:
  team: infra

priorityClassName: ""

secrets: []
configMaps: {}

volumeMounts: []
volumes: []

extraObjects: []
